### ISSUE TITLE
Including @vue/composition-api in peerDeps breaks installing on Vue3

### ISSUE THREAD

**Issue by ProjektGopher** [victorgarciaesgi/vue-chart-3#75]
## Describe the bug
v3.0.5 has @vue/composition-api as a peer dependency, which itself has a dependency on Vue < 3. This creates unresolvable dependencies when installing with vue3 which weren't present in v3.0.2

## To Reproduce
```bash
npm install vue@3.2.26
npm install vue-chart-3
```

## Version of `vue-chart-3`
- [x] *v3.0.5*
- [ ] *v3.0.2*

## Version of Vue

- [x] Vue 3
- [ ] Vue 2

**Comment by ProjektGopher** [comment]
I haven't made a pr for this, as looking through git blame history it appears this was added as part of a bugfix for another issue.

**Comment by victorgarciaesgi** [comment]
Hi! Yeah i don't know why it was included, removing it and publishing :)

**Comment by victorgarciaesgi** [comment]
done in `3.0.6`

**Comment by SharpSeeEr** [comment]
Having this same issue.  npm still shows 3.0.5 as the latest version.  Maybe I'm just jumping the gun and the update hasn't been pushed just yet?

**Comment by victorgarciaesgi** [comment]
@SharpSeeEr oh yeah I think i messed up, doing it tomorrow sorry i can't tonight

**Comment by victorgarciaesgi** [comment]
Fixed!

**Comment by victorgarciaesgi** [comment]
`3.0.7` sorry still wasn't there :(

**Comment by SharpSeeEr** [comment]
No worries on the time thing!  Fixed and published within 2 days is still something that I believe is above what would be considered a fast response!  Thanks for all your effort!
