### ISSUE TITLE
LineChar Labels not reactive

### ISSUE THREAD

**Issue by BITRU** [victorgarciaesgi/vue-chart-3#78]
## Version of `vue-chart-3`
 v2.0.5

## Version of Vue
- [ ] Vue 2

I have a Line chat that get data from vuex getter.
Labels - line under chart with time.
If show today it show only labels awalable today.
If I select previous date with all time labes avalable, chat data updated, however label stay the same as from today.
But when I disable/enable label (NOT LEBELS, just data label) labels under char updates and all chat visible. So my getter have correct data.

**Comment by victorgarciaesgi** [comment]
Can you make a codesandbox repro of your bug so I can look at it? :)

**Comment by victorgarciaesgi** [comment]
Looks a lot like #80 , I just published a fix for this issue on `v2.1.1`, tell me if this fixes it for you :)

**Comment by gregveres** [comment]
I just tried it and it did not fix the issue. Sorry. 

```
02-15 11:20:46 2> yarn why vue-chart-3
yarn why v1.22.17
[1/4] Why do we have the module "vue-chart-3"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "vue-chart-3@2.1.1"
info Has been hoisted to "vue-chart-3"
info This module exists because it's specified in "dependencies".
info Disk size without dependencies: "64KB"
info Disk size with unique dependencies: "4.31MB"
info Disk size with transitive dependencies: "4.31MB"
info Number of shared dependencies: 4
Done in 0.62s.
```

For now I am going with a changing :key on the BarChart to get Vue to recreate the chart each time the data changes.

**Comment by victorgarciaesgi** [comment]
So it was not related, i will try to fix it when I have time :)

**Comment by victorgarciaesgi** [comment]
Should be the same bug as Vue 3 #108 , i will publish a fix soon @gregveres @BITRU

**Comment by victorgarciaesgi** [comment]
Fixed in `2.1.3` !

**Comment by victorgarciaesgi** [comment]
Sorry for the wait

**Comment by gregveres** [comment]
Thank you. I will upgrade and try it out after I get this current feature finished.

**Comment by gregveres** [comment]
It's is behaving differently now. Actually, I guess I can say that this issue is fixed, but the fix introduced a new issue that is very much related. 

Here is the code I am using:
```
 <component
          :is="graph"
          chartId="allTimes"
          :chartData="data.summary.value.allTimesData"
          :options="data.summary.value.allTimesOptions"
          class="my-8"
        />
```
graph is BarChart from 'vue-chart-3'

Here is the first graph. This is has 5 datasets and 31 labels:
![image](https://user-images.githubusercontent.com/12899823/160296880-b4f6f711-250e-4704-999d-465ff8f282a4.png)

Then I change the date so that I have 4 datasets and 31 labels. The graph should look like this:
![image](https://user-images.githubusercontent.com/12899823/160296928-76f4444a-36cf-490a-ad3d-be4fd25103ef.png)

(this is the graph I get if I select this date for the initial query) But it looks like this instead:
![image](https://user-images.githubusercontent.com/12899823/160296963-1ea710fc-defc-4c24-bdaa-2c69c2372c90.png)

What appears to be happening is that the old datasets were not cleared out. My data only includes the new smaller dataset, but the old one wasn't cleared out.  You can see this in the legend. There are two datasets called Available. And you can see the line across all the bars just at about the 16 mark. 

Here is what the data looks like in the Vue Debugger for the first graph and then the last graph. Notice that my data being fed to the BarChart no longer has the original data, it has a completely new dataset.
![image](https://user-images.githubusercontent.com/12899823/160297113-40dc1fd1-26e7-493c-af8a-ade00579fd28.png)

and when I change the input data to get the third graph above ...
![image](https://user-images.githubusercontent.com/12899823/160297148-7ccf454b-56f0-4713-9657-c431ff7a7405.png)

**Comment by gregveres** [comment]
Looking at the data further, it seems like it is only keeping in one of the original 5 datasets, the one called Available from the first 5 datasets and then when I swap out the 5 datasets for a new set of 4 datasets, it keeps "Available" from the first set of datasets and adds that to the new 4 datasets. 

Ah, here is an idea of what might be happening...
I tried something else. I made sure that the first graph now had 6 datasets instead of 5. Then I switched to a date that only had 4 datasets. The result is that the graph has 6 datasets instead of 4. 

So I think what is happening is that you are not clearning out the old array of datasets, instead you (or Chart.js) is overwriting the array elements with the new data. When the new data has more datasets than the old data, this works just fine. But when the new datasets have less elements than the old data, the 'extra' old data hangs around rather than getting wiped out.

**Comment by victorgarciaesgi** [comment]
@gregveres Thanks for the detailled feedback! I will look further into the problem with your dataset
